{.passL: "-fobjc-arc -framework Cocoa -L$HOME/.nimble/lib -lcocoa"}

import Cocoa / [NSButton,
                NSCheckbox,
                NSColordialog,
                NSCombobox,
                NSContainer,
                NSDialog,
                NSFunctions,
                NSLabel,
                NSLine,
                NSListbox,
                NSMenu,
                NSMessagebox,
                NSOpendialog,
                NSRadioButton,
                NSSavedialog,
                NSSlider,
                NSTabView,
                NSTableview,
                NSTextedit,
                NSTextfield,
                NSWindow
]

export  NSButton,
        NSCheckbox,
        NSColordialog,
        NSCombobox,
        NSContainer,
        NSDialog,
        NSFunctions,
        NSLabel,
        NSLine,
        NSListbox,
        NSMenu,
        NSMessagebox,
        NSOpendialog,
        NSRadioButton,
        NSSavedialog,
        NSSlider,
        NSTabView,
        NSTableview,
        NSTextedit,
        NSTextfield,
        NSWindow
